#!/bin/bash

if [ -z "$1" ]; then
	echo "Must specify module (e.g. app)"
    exit 1
fi

if [ -z "$2" ]; then
	echo "Must specify build type, starting w/ capital letter (e.g. Debug, DebugFree, ReleasePaid)"
    exit 1
fi

if [ -z "$3" ]; then
	echo "Must specify package/class/test/regex. Examples:"
	echo "* fully qualified class: com.example.MytestClass"
	echo "* fully qualified method: com.example.MytestClass#myTest"
	echo "* wildcard on package: com.example.*"
	echo "* wildcard on class: MytestClass*"
	echo "* wildcard on method: methodname*"
	echo "(note: does not support leading wildcard e.g. *TestClass)"
  exit 1
fi

echo ===============
echo Running $1:connected$2AndroidTest for: $3
echo ===============
./gradlew $1:connected$2AndroidTest -Pandroid.testInstrumentationRunnerArguments.tests_regex=$3
